const mongoose = require('mongoose')

const PaymentSchema = mongoose.Schema({
    command:{
        type : String,
        require:true
    },
    access_code:{
        type:String,
        required:true
    },
    merchant_id:{
        type:String,
        required:true
    },
    order_id:{
        type:Number,
        required:true
    },
    amount:{
        type:Number,
        required:true
    },
    redirect_url:{
        type:String,
        required:true
    },
    cancel_url:{
        type:String,
        required:true
    },
    billing_name:{
        type:String,
        required:true
    },
    billing_address:{
        type:String,
        required:true
    },
    billing_city:{
        type:String,
        required:true
    },
    billing_state:{
        type:String,
        required:true
    },
    billing_zip:{
        type:String,
        required:true
    },
    billing_country:{
        type:String,
        required:true
    },
    billing_tel:{
        type:String,
        required:true
    },
    billing_email:{
        type:String,
        required:true
    },
    delivery_name:{
        type:String,
        required:true
    },
    delivery_address:{
        type:String,
        required:true
    },
    delivery_city:{
        type:String,
        required:true
    },
    delivery_state:{
        type:String,
        required:true
    },
    delivery_zip:{
        type:String,
        required:true
    },
    delivery_country:{
        type:String,
        required:true
    },
    delivery_tel:{
        type:String,
        required:true
    },
    merchant_param1:{
        type:String,
        required:true
    },
    merchant_param2:{
        type:String,
        required:true
    },
    merchant_param3:{
        type:String,
        required:true
    },
    merchant_param4:{
        type:String,
        required:true
    }
})

module.exports = mongoose.model('paymentSchema',PaymentSchema)


        